export const FIELD_WIDTH = 15;
export const FIELD_HEIGHT = 9;
export const TEAM_SIZE = 5;
export const MAX_SCORE = 3;

export const GOALS = {
  0: { x: 0, y: 4 },
  1: { x: 14, y: 4 },
};

export const POSITION_LABELS = {
  GK: "Вратарь",
  DEF: "Защитник",
  MID: "Полузащитник",
  FWD: "Нападающий",
};

export const TEAM_DEFS = [
  {
    id: 0,
    name: "Алые Кометы",
    shortName: "Алые",
    attackDirection: 1,
    color: "#d94f30",
    colorDark: "#8f2f1c",
    accent: "#ffd468",
    bg: "#2d1510",
  },
  {
    id: 1,
    name: "Лазурные Волки",
    shortName: "Лазурные",
    attackDirection: -1,
    color: "#2f77d0",
    colorDark: "#1d447f",
    accent: "#9be2ff",
    bg: "#101d31",
  },
];

export const ABILITIES = {
  catReflexes: {
    id: "catReflexes",
    label: "Кошачья реакция",
    description: "Следующее спасение: +4 к игре на линии.",
    contexts: ["save"],
  },
  ironWall: {
    id: "ironWall",
    label: "Железная стена",
    description: "Следующий отбор или подкат: +4 к силе отбора.",
    contexts: ["tackle", "slide"],
  },
  threadPass: {
    id: "threadPass",
    label: "Разрезающий пас",
    description: "Следующий пас: +2 к дальности и без попытки перехвата.",
    contexts: ["pass"],
  },
  untouchable: {
    id: "untouchable",
    label: "Неуловимый",
    description: "Следующий дриблинг или защита от отбора: +4 к дриблингу.",
    contexts: ["dribble", "defendTackle"],
  },
  longShot: {
    id: "longShot",
    label: "Удар с центра",
    description: "Следующий удар: +5 к атаке.",
    contexts: ["shoot"],
  },
};

export const PLAYER_CATALOG = [
  {
    id: "gk-semyon-shchitov",
    name: "Семён Щитов",
    position: "GK",
    cost: 10,
    shot: 1,
    pass: 3,
    throughPass: false,
    receive: 4,
    dribble: 1,
    speed: 2,
    tackle: 1,
    intercept: 6,
    goalkeeping: 4,
  },
  {
    id: "gk-pavel-lentochkin",
    name: "Павел Ленточкин",
    position: "GK",
    cost: 10,
    shot: 1,
    pass: 4,
    throughPass: false,
    receive: 4,
    dribble: 1,
    speed: 2,
    tackle: 1,
    intercept: 6,
    goalkeeping: 3,
  },
  {
    id: "gk-artur-kordon",
    name: "Артур Кордон",
    position: "GK",
    cost: 20,
    shot: 1,
    pass: 4,
    throughPass: false,
    receive: 4,
    dribble: 2,
    speed: 2,
    tackle: 2,
    intercept: 5,
    goalkeeping: 5,
  },
  {
    id: "gk-denis-barierov",
    name: "Денис Барьеров",
    position: "GK",
    cost: 30,
    shot: 2,
    pass: 5,
    throughPass: true,
    receive: 3,
    dribble: 2,
    speed: 2,
    tackle: 2,
    intercept: 5,
    goalkeeping: 6,
    abilityId: "catReflexes",
  },
  {
    id: "gk-ilya-monolit",
    name: "Илья Монолит",
    position: "GK",
    cost: 40,
    shot: 2,
    pass: 5,
    throughPass: true,
    receive: 3,
    dribble: 2,
    speed: 2,
    tackle: 2,
    intercept: 4,
    goalkeeping: 7,
    abilityId: "catReflexes",
  },
  {
    id: "def-egor-hardov",
    name: "Егор Хардов",
    position: "DEF",
    cost: 10,
    shot: 2,
    pass: 3,
    throughPass: false,
    receive: 4,
    dribble: 2,
    speed: 3,
    tackle: 5,
    intercept: 4,
    goalkeeping: 0,
  },
  {
    id: "def-kirill-polev",
    name: "Кирилл Полев",
    position: "DEF",
    cost: 20,
    shot: 2,
    pass: 3,
    throughPass: false,
    receive: 4,
    dribble: 2,
    speed: 3,
    tackle: 6,
    intercept: 4,
    goalkeeping: 0,
  },
  {
    id: "def-maksim-zubov",
    name: "Максим Зубов",
    position: "DEF",
    cost: 20,
    shot: 2,
    pass: 4,
    throughPass: false,
    receive: 4,
    dribble: 2,
    speed: 4,
    tackle: 6,
    intercept: 3,
    goalkeeping: 0,
  },
  {
    id: "def-oleg-betonov",
    name: "Олег Бетонов",
    position: "DEF",
    cost: 30,
    shot: 3,
    pass: 4,
    throughPass: true,
    receive: 3,
    dribble: 3,
    speed: 4,
    tackle: 7,
    intercept: 3,
    goalkeeping: 0,
    abilityId: "ironWall",
  },
  {
    id: "def-roman-bastion",
    name: "Роман Бастион",
    position: "DEF",
    cost: 40,
    shot: 3,
    pass: 4,
    throughPass: true,
    receive: 3,
    dribble: 3,
    speed: 4,
    tackle: 8,
    intercept: 2,
    goalkeeping: 0,
    abilityId: "ironWall",
  },
  {
    id: "mid-lev-ritmov",
    name: "Лев Ритмов",
    position: "MID",
    cost: 10,
    shot: 3,
    pass: 5,
    throughPass: true,
    receive: 4,
    dribble: 3,
    speed: 4,
    tackle: 3,
    intercept: 5,
    goalkeeping: 0,
  },
  {
    id: "mid-daniil-mostovoy",
    name: "Даниил Мостовой",
    position: "MID",
    cost: 20,
    shot: 3,
    pass: 6,
    throughPass: true,
    receive: 3,
    dribble: 4,
    speed: 4,
    tackle: 3,
    intercept: 4,
    goalkeeping: 0,
  },
  {
    id: "mid-timur-tempo",
    name: "Тимур Темпо",
    position: "MID",
    cost: 30,
    shot: 4,
    pass: 6,
    throughPass: true,
    receive: 3,
    dribble: 4,
    speed: 5,
    tackle: 4,
    intercept: 4,
    goalkeeping: 0,
    abilityId: "threadPass",
  },
  {
    id: "mid-yaroslav-dirizher",
    name: "Ярослав Дирижёр",
    position: "MID",
    cost: 30,
    shot: 4,
    pass: 7,
    throughPass: true,
    receive: 2,
    dribble: 5,
    speed: 5,
    tackle: 4,
    intercept: 3,
    goalkeeping: 0,
    abilityId: "threadPass",
  },
  {
    id: "mid-nikita-compass",
    name: "Никита Компас",
    position: "MID",
    cost: 40,
    shot: 5,
    pass: 7,
    throughPass: true,
    receive: 2,
    dribble: 5,
    speed: 5,
    tackle: 4,
    intercept: 3,
    goalkeeping: 0,
    abilityId: "threadPass",
  },
  {
    id: "fwd-anton-vyvorot",
    name: "Антон Выворот",
    position: "FWD",
    cost: 10,
    shot: 5,
    pass: 3,
    throughPass: false,
    receive: 4,
    dribble: 4,
    speed: 5,
    tackle: 2,
    intercept: 6,
    goalkeeping: 0,
  },
  {
    id: "fwd-georgiy-rysak",
    name: "Георгий Рысь",
    position: "FWD",
    cost: 20,
    shot: 6,
    pass: 4,
    throughPass: false,
    receive: 3,
    dribble: 5,
    speed: 5,
    tackle: 2,
    intercept: 5,
    goalkeeping: 0,
  },
  {
    id: "fwd-viktor-obvod",
    name: "Виктор Обвод",
    position: "FWD",
    cost: 30,
    shot: 6,
    pass: 4,
    throughPass: true,
    receive: 3,
    dribble: 6,
    speed: 6,
    tackle: 3,
    intercept: 5,
    goalkeeping: 0,
    abilityId: "untouchable",
  },
  {
    id: "fwd-sergey-stinger",
    name: "Сергей Стингер",
    position: "FWD",
    cost: 40,
    shot: 7,
    pass: 5,
    throughPass: true,
    receive: 2,
    dribble: 6,
    speed: 6,
    tackle: 3,
    intercept: 4,
    goalkeeping: 0,
    abilityId: "longShot",
  },
  {
    id: "fwd-alex-storm",
    name: "Алекс Шторм",
    position: "FWD",
    cost: 40,
    shot: 8,
    pass: 5,
    throughPass: true,
    receive: 2,
    dribble: 7,
    speed: 6,
    tackle: 3,
    intercept: 4,
    goalkeeping: 0,
    abilityId: "longShot",
  },
];
